using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TestAPI.Models;

namespace TestAPITests.Classes
{
    [TestClass]
    public class CreateCustomer_MissingFields_Failure
    {
        [TestMethod]
        public void CreateCustomer()
        {
            int mockId = 0;  //Id is generated by the database, so we use a mock one in unit test.

            Customer customer = new Customer()
            {
                CustomerId = mockId,
                FirstName = "Kia",
                Address = "Helsinkintie 12",
                City = "Helsinki",
                DateCreated = DateTime.Today
            };

            Customer c1 = new Customer();

            var validationContext = new ValidationContext(c1.LastName);
            var result = new List<ValidationResult>();

            var isValid = Validator.TryValidateValue(customer.LastName, validationContext, result);

            Assert.IsFalse(isValid);
        }
    }
}
